# Generated by Django 3.0.3 on 2020-07-19 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_item_lab_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
