# Generated by Django 3.0.3 on 2020-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_labtest_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media_/pdf/'),
        ),
    ]
