# Generated by Django 3.0.3 on 2020-07-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplecollector', '0004_delete_samplecollection'),
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samplecollector.SampleCollector'),
        ),
    ]
