# Generated by Django 3.0.3 on 2020-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='photo',
            field=models.ImageField(null=True, upload_to='media_/lab_pics/'),
        ),
    ]
