# Generated by Django 3.0.3 on 2020-04-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mob_no',
            field=models.IntegerField(max_length=12),
        ),
    ]
