# Generated by Django 3.0.3 on 2020-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200406_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mob_no',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
