# Generated by Django 3.0.3 on 2020-04-09 09:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physiotherapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('speciality', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, default='physio.jpeg', upload_to='Physio_pics')),
                ('house_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undisclosed')], max_length=1)),
                ('dob', models.DateField()),
                ('mob_no', models.BigIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time_start', models.CharField(blank=True, choices=[('09:00:00', '9 am'), ('10:00:00', '10 am'), ('11:00:00', '11 am'), ('12:00:00', '12 am'), ('13:00:00', '1 pm'), ('14:00:00', '2 pm'), ('15:00:00', '3 pm'), ('16:00:00', '4 pm'), ('17:00:00', '5 pm'), ('18:00:00', '6 pm')], max_length=200, null=True)),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentPhysio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'Upcoming'), ('C', 'Completed')], max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Slot')),
            ],
        ),
    ]
