# Generated by Django 3.0.3 on 2020-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotherapist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='physiotherapist',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='profile_pic',
            field=models.ImageField(blank=True, default='physio.jpeg', upload_to='Physio_pics'),
        ),
    ]
