# Generated by Django 3.0.3 on 2020-04-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentphysio',
            name='slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Slot'),
        ),
    ]
