# Generated by Django 3.0.3 on 2020-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0002_auto_20200409_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
