# Generated by Django 3.0.3 on 2020-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0003_physiotherapist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist',
            name='mob_no',
            field=models.BigIntegerField(),
        ),
    ]
