# Generated by Django 3.0.3 on 2020-04-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0004_auto_20200406_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
