# Generated by Django 3.0.3 on 2020-04-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200406_1344'),
        ('physiotherapist', '0005_auto_20200406_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('Physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentPhysio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'Upcoming'), ('C', 'Completed')], max_length=1)),
                ('Physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Slot')),
            ],
        ),
    ]
