# Generated by Django 3.0.3 on 2020-04-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0008_auto_20200408_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='Physiotherapist',
        ),
    ]
