# Generated by Django 3.0.3 on 2020-04-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0010_auto_20200409_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentphysio',
            name='slot',
        ),
        migrations.AddField(
            model_name='slot',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.AppointmentPhysio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
