# Generated by Django 3.0.3 on 2020-04-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0011_auto_20200409_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointmentphysio',
            name='slot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Slot'),
            preserve_default=False,
        ),
    ]
