# Generated by Django 3.0.3 on 2020-07-01 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0012_auto_20200409_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appointmentphysio',
            name='slot',
        ),
        migrations.AddField(
            model_name='slot',
            name='physiotherapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist'),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.CharField(blank=True, choices=[('09:00:00', '9 am'), ('12:00:00', '12 pm'), ('16:00:00', '4 pm')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('physiotherapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.BookingDate'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('physiotherapist', 'start_time', 'date')},
        ),
        migrations.RemoveField(
            model_name='slot',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='time_start',
        ),
    ]
