# Generated by Django 3.0.3 on 2020-07-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0014_physiotherapist_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physiotherapist_complaint_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specify_type', models.CharField(blank=True, choices=[('SALARY', 'SALARY'), ('BOOKING', 'BOOKING'), ('OTHER/FEEDBACK', 'OTHER/FEEDBACK')], max_length=200, null=True)),
                ('description', models.TextField()),
                ('physiotherapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist')),
            ],
        ),
        migrations.DeleteModel(
            name='Physiotherapist_complaint',
        ),
    ]
