# Generated by Django 3.0.3 on 2020-07-01 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0016_auto_20200701_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotherapist',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media_/physio_profile_pic/'),
            preserve_default=False,
        ),
    ]
