# Generated by Django 3.0.3 on 2020-07-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0017_auto_20200701_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist_complaint_feedback',
            name='specify_type',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('BOOKING', 'BOOKING'), ('OTHER/FEEDBACK', 'OTHER/FEEDBACK')], default='Complaint', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.CharField(blank=True, choices=[('09:00:00', '9 am'), ('10:00:00', '10 am'), ('11:00:00', '11 am'), ('12:00:00', '12 pm'), ('13:00:00', '1 pm'), ('14:00:00', '2 pm'), ('15:00:00', '3 pm'), ('16:00:00', '4 pm'), ('17:00:00', '5 pm'), ('18:00:00', '6 pm')], max_length=200, null=True),
        ),
    ]
