# Generated by Django 3.0.3 on 2020-07-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0018_auto_20200705_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentPhysio',
        ),
    ]
