# Generated by Django 3.0.3 on 2020-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lab_name', models.CharField(default='', max_length=100)),
                ('lab_registration', models.CharField(default='', max_length=100)),
                ('lab_owner', models.CharField(max_length=350)),
                ('owner_name', models.CharField(default='', max_length=100)),
                ('lab_address', models.CharField(default='', max_length=300)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('mobile_no', models.BigIntegerField()),
                ('rating', models.FloatField(default='10.0')),
            ],
        ),
    ]
