# Generated by Django 3.0.3 on 2020-04-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_lab_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='lab_id',
        ),
    ]
