# Generated by Django 3.0.3 on 2020-07-09 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('speciality', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('profile_photo', models.ImageField(upload_to='media_/physio_profile_pic/')),
                ('house_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undisclosed')], max_length=1)),
                ('dob', models.DateField()),
                ('mob_no', models.BigIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse_complaint_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specify_type', models.CharField(choices=[('SALARY', 'SALARY'), ('BOOKING', 'BOOKING'), ('OTHER/FEEDBACK', 'OTHER/FEEDBACK')], max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENT TO ADMIN', 'SENT TO ADMIN'), ('RESOLVED', 'RESOLVED')], default='SENT TO ADMIN', max_length=200)),
                ('description', models.TextField()),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.Nurse')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.Nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, choices=[('09:00:00', '9 am'), ('10:00:00', '10 am'), ('11:00:00', '11 am'), ('12:00:00', '12 pm'), ('13:00:00', '1 pm'), ('14:00:00', '2 pm'), ('15:00:00', '3 pm'), ('16:00:00', '4 pm'), ('17:00:00', '5 pm'), ('18:00:00', '6 pm')], max_length=200, null=True)),
                ('slot_status', models.BooleanField(default=False)),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.BookingDate')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.Nurse')),
            ],
            options={
                'unique_together': {('nurse', 'start_time', 'date')},
            },
        ),
    ]
