# Generated by Django 3.0.3 on 2020-07-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='speciality',
        ),
    ]
