# Generated by Django 3.0.3 on 2020-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist',
            name='mob_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
