# Generated by Django 3.0.3 on 2020-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_remove_nurse_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='profile_photo',
            field=models.ImageField(upload_to='media_/nuse_profile_pic/'),
        ),
    ]
