# Generated by Django 3.0.3 on 2020-07-19 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
        ('samplecollector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('is_collected', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samplecollector.SampleCollector')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab1.Test1')),
            ],
        ),
    ]
