# Generated by Django 3.0.3 on 2020-07-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplecollector', '0003_samplecollection_lab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleCollection',
        ),
    ]
