# Generated by Django 3.0.3 on 2020-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='discounted_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
